import { useState, useEffect } from "react";

/* ═══════════════════════════════════════════════════════════════
   LAUNCHGUARD v3 — Production Microservices UI
   Nav: Dashboard | Sessions | Admin | Settings | Guide | + New Check
   Features: Regulation Engine, Governance (Sign-offs, Gates, Certs),
             Drift Monitor, Risk Trends, Session Comparison
   ═══════════════════════════════════════════════════════════════ */

const T={bg:"#07080c",bg2:"#0c0e14",sf:"#11131b",sf2:"#171b27",sf3:"#1d2234",bd:"#1a1e30",bd2:"#252b42",gn:"#22c55e",gn2:"#4ade80",gnA:"rgba(34,197,94,.10)",gnA2:"rgba(34,197,94,.22)",pr:"#7c3aed",pr2:"#a78bfa",prA:"rgba(124,58,237,.10)",rd:"#ef4444",rd2:"#f87171",rdA:"rgba(239,68,68,.10)",or:"#f59e0b",or2:"#fbbf24",orA:"rgba(245,158,11,.10)",bl:"#3b82f6",bl2:"#60a5fa",blA:"rgba(59,130,246,.10)",tl:"#14b8a6",tlA:"rgba(20,184,166,.10)",pk:"#ec4899",pkA:"rgba(236,72,153,.10)",yl:"#eab308",tx:"#f1f5f9",tx2:"#94a3b8",tx3:"#64748b",tx4:"#334155"};
const F=`'Inter','SF Pro Display',system-ui,sans-serif`;
const M=`'JetBrains Mono','SF Mono',monospace`;
const CSS=`@import url('https://fonts.googleapis.com/css2?family=Inter:wght@300;400;500;600;700;800;900&display=swap');*{box-sizing:border-box;margin:0;padding:0}::-webkit-scrollbar{width:5px}::-webkit-scrollbar-thumb{background:${T.bd2};border-radius:3px}::-webkit-scrollbar-track{background:transparent}input::placeholder,textarea::placeholder{color:${T.tx4}}@keyframes fadeUp{from{opacity:0;transform:translateY(10px)}to{opacity:1;transform:translateY(0)}}@keyframes pulse{0%,100%{opacity:1}50%{opacity:.35}}@keyframes spin{to{transform:rotate(360deg)}}@keyframes glow{0%,100%{box-shadow:0 0 8px rgba(124,58,237,.12)}50%{box-shadow:0 0 20px rgba(124,58,237,.25)}}.fu{animation:fadeUp .45s cubic-bezier(.16,1,.3,1) both}.s1{animation-delay:.04s}.s2{animation-delay:.08s}.s3{animation-delay:.12s}.s4{animation-delay:.16s}.s5{animation-delay:.2s}.s6{animation-delay:.24s}`;

// ── Primitives ──
function Bdg({children,c="gn",sz="sm",s={}}){const m={gn:[T.gnA,T.gn2],pr:[T.prA,T.pr2],rd:[T.rdA,T.rd2],or:[T.orA,T.or2],bl:[T.blA,T.bl2],tl:[T.tlA,T.tl],pk:[T.pkA,T.pk]}[c]||[T.gnA,T.gn2];const p=sz==="xs"?"2px 6px":sz==="lg"?"5px 14px":"3px 9px";const f=sz==="xs"?10:sz==="lg"?12:11;return <span style={{background:m[0],color:m[1],padding:p,borderRadius:5,fontSize:f,fontWeight:600,whiteSpace:"nowrap",display:"inline-flex",alignItems:"center",gap:3,...s}}>{children}</span>;}

function Crd({children,style={},onClick,className=""}){return <div className={className} onClick={onClick} style={{background:T.sf,border:`1px solid ${T.bd}`,borderRadius:10,padding:20,transition:"border-color .15s",cursor:onClick?"pointer":"default",...style}} onMouseEnter={e=>{if(onClick)e.currentTarget.style.borderColor=T.bd2}} onMouseLeave={e=>{e.currentTarget.style.borderColor=T.bd}}>{children}</div>;}

function Btn({children,v="default",sz="sm",onClick,disabled,s={}}){const vars={primary:{bg:T.pr,c:"#fff",bd:"none"},cta:{bg:T.rd,c:"#fff",bd:"none"},danger:{bg:"transparent",c:T.rd2,bd:`1px solid ${T.rd}35`},success:{bg:T.gnA2,c:T.gn2,bd:`1px solid ${T.gn}35`},ghost:{bg:"transparent",c:T.tx2,bd:`1px solid ${T.bd}`},default:{bg:T.sf2,c:T.tx2,bd:`1px solid ${T.bd}`}}[v]||{bg:T.sf2,c:T.tx2,bd:`1px solid ${T.bd}`};const p=sz==="xs"?"4px 8px":sz==="lg"?"11px 24px":"6px 13px";const f=sz==="xs"?11:sz==="lg"?14:12;return <button onClick={onClick} disabled={disabled} style={{background:vars.bg,color:disabled?T.tx4:vars.c,border:vars.bd,borderRadius:6,padding:p,fontSize:f,fontWeight:600,cursor:disabled?"default":"pointer",fontFamily:F,transition:"all .12s",...s}}>{children}</button>;}

function PB({pct,color=T.gn,h=6}){return <div style={{flex:1,height:h,background:T.sf3,borderRadius:h,overflow:"hidden"}}><div style={{height:"100%",width:`${pct}%`,background:color,borderRadius:h,transition:"width 1s cubic-bezier(.16,1,.3,1)"}}/></div>;}

function CS({score,sz=88}){const r=(sz-10)/2,c=2*Math.PI*r,off=c-(score/100)*c;const col=score>=80?T.gn:score>=60?T.or:score>=40?T.or:T.rd;const gr=score>=90?"A":score>=80?"B":score>=70?"C":score>=60?"D":"F";return <div style={{position:"relative",width:sz,height:sz}}><svg width={sz} height={sz} style={{transform:"rotate(-90deg)"}}><circle cx={sz/2} cy={sz/2} r={r} fill="none" stroke={T.sf3} strokeWidth={5}/><circle cx={sz/2} cy={sz/2} r={r} fill="none" stroke={col} strokeWidth={5} strokeDasharray={c} strokeDashoffset={off} strokeLinecap="round" style={{transition:"stroke-dashoffset 1.5s cubic-bezier(.16,1,.3,1)"}}/></svg><div style={{position:"absolute",inset:0,display:"flex",flexDirection:"column",alignItems:"center",justifyContent:"center"}}><span style={{fontSize:sz*.28,fontWeight:800,color:col,lineHeight:1}}>{score}</span><span style={{fontSize:9,color:T.tx4,fontWeight:700,marginTop:1}}>{gr}</span></div></div>;}

function Lbl({children}){return <div style={{fontSize:10,fontWeight:700,color:T.tx4,letterSpacing:1.2,textTransform:"uppercase",marginBottom:12}}>{children}</div>;}
function Spinner({sz=13,c=T.pr2}){return <div style={{width:sz,height:sz,border:`2px solid ${T.sf3}`,borderTopColor:c,borderRadius:"50%",animation:"spin .6s linear infinite"}}/>;}

// ── Pipeline ──
const LOGS=[["Parsing feature description...","Extracting domain context...","Generating release spec...","Identifying personas & stories...","Scoring risks...","Building checklist...","Navigator complete → handoff"],["Analysing spec for edge cases...","Generating test strategy...","Creating test cases...","Defining guardrails...","Sentinel complete → handoff"],["Synthesising release notes...","Generating GTM copy...","Building pitch deck...","Herald complete"]];

function Pipeline({phase,showLogs=false}){
  const ag=[{n:"Navigator",c:T.gn},{n:"Sentinel",c:T.pr2},{n:"Herald",c:T.or2}];
  const[logs,setLogs]=useState([]);
  useEffect(()=>{if(!showLogs||phase<0||phase>2)return;const ls=LOGS[phase]||[];let i=0;const iv=setInterval(()=>{if(i<ls.length){setLogs(p=>[...p.slice(-10),{t:new Date().toISOString().slice(11,19),m:ls[i],p:phase}]);i++;}else clearInterval(iv);},500);return()=>clearInterval(iv);},[phase,showLogs]);
  return <div><div style={{display:"flex",alignItems:"center",justifyContent:"center",gap:0,padding:"12px 0"}}>{ag.map((a,i)=>{const done=phase>i,act=phase===i;return <div key={i} style={{display:"flex",alignItems:"center"}}>{i>0&&<div style={{width:40,height:2,background:done?a.c+"60":T.bd,transition:"all .4s"}}/>}<div style={{display:"flex",alignItems:"center",gap:5,padding:"6px 12px",borderRadius:7,border:`1px solid ${done?a.c+"50":act?a.c:T.bd}`,background:done?a.c+"0a":act?a.c+"08":"transparent",animation:act?"glow 2s ease infinite":"none"}}>{done&&<span style={{color:T.gn,fontSize:11,fontWeight:700}}>✓</span>}{act&&<Spinner sz={11} c={a.c}/>}<div><div style={{fontSize:12,color:done||act?a.c:T.tx4,fontWeight:600}}>{a.n}</div></div></div></div>;})}{phase>=3&&<Bdg c="gn" s={{marginLeft:10}}>✓ COMPLETE</Bdg>}</div>{showLogs&&logs.length>0&&<div style={{background:T.bg2,border:`1px solid ${T.bd}`,borderRadius:7,padding:"8px 12px",marginTop:6,maxHeight:120,overflow:"auto",fontFamily:M,fontSize:11}}>{logs.map((l,i)=><div key={i} style={{padding:"2px 0",color:l.p===0?T.gn:l.p===1?T.pr2:T.or2,opacity:i===logs.length-1?1:.5}}><span style={{color:T.tx4,marginRight:8}}>{l.t}</span>{l.m}</div>)}</div>}</div>;
}

// ── Heatmap ──
function Heatmap({risks}){const lvl=["Low","Medium","High"];const mx={};lvl.forEach(l=>lvl.forEach(i=>{mx[`${l}-${i}`]=[];}));risks.forEach(r=>{const k=`${r.likelihood||"Medium"}-${r.impact||"High"}`;if(mx[k])mx[k].push(r);});const cc=(l,i)=>{const s=lvl.indexOf(l)+lvl.indexOf(i);return s>=3?T.rdA:s>=2?T.orA:T.gnA;};return <div><div style={{display:"grid",gridTemplateColumns:"50px repeat(3,1fr)",gap:2}}><div/>{lvl.map(l=><div key={l} style={{textAlign:"center",fontSize:9,fontWeight:600,color:T.tx4,padding:"5px 0"}}>{l}</div>)}{[...lvl].reverse().map(lik=><div key={lik} style={{display:"contents"}}><div style={{display:"flex",alignItems:"center",justifyContent:"flex-end",paddingRight:6,fontSize:9,fontWeight:600,color:T.tx4}}>{lik}</div>{lvl.map(imp=>{const items=mx[`${lik}-${imp}`];return <div key={`${lik}-${imp}`} style={{background:items.length?cc(lik,imp):T.sf2,border:`1px solid ${T.bd}`,borderRadius:5,padding:5,minHeight:36}}>{items.map((r,i)=><div key={i} style={{fontSize:9,color:T.tx2}}>{r.n.slice(0,25)}</div>)}</div>;})}</div>)}</div></div>;}

// ── Data ──
const S_DATA=[
  {id:"legal",title:"AI Legal Email Drafting Assistant",type:"demo",icon:"⚖️",date:"02/03/2026, 23:30",bc:T.pr,desc:"An AI assistant that drafts client-facing legal emails from short bullet-point notes. High compliance and data sensitivity.",tags:[{l:"Full Spec",c:"gn"},{l:"High Risks",c:"rd"}],risks:[{id:"R1",n:"Cross-matter data leakage",s:"High",cat:"Privacy",likelihood:"High",impact:"High"},{id:"R2",n:"Incorrect legal statements",s:"High",cat:"Safety",likelihood:"Medium",impact:"High"},{id:"R3",n:"Tone mismatch",s:"Medium",cat:"UX/Business",likelihood:"Medium",impact:"Medium"},{id:"R4",n:"Over-reliance on AI",s:"Medium",cat:"UX/Business",likelihood:"High",impact:"Medium"}],st:{risks:4,check:8,tests:5,guard:4,score:68},sb:[2,2,0],cl:["Per-matter context scoping confirmed","Tone templates reviewed by legal staff","Mandatory review workflow — no auto-send","Cross-client leakage test suite executed","Legal accuracy review by counsel","User guide on AI limitations distributed"],co:["Engineering","Legal","Engineering","QA","Legal","Product"],gtm:{h:"Draft legal emails in minutes.",t:"Speed up communication without losing control.",b:4,f:2},signoffs:[{role:"PM",status:"approved",user:"Sarah K.",at:"02/03 23:45"},{role:"Legal",status:"approved",user:"James L.",at:"03/03 09:12"},{role:"QA",status:"pending",user:null,at:null},{role:"Security",status:"pending",user:null,at:null}],euTier:"High-Risk",owasp:["LLM06","LLM08","LLM09"],nist:["MAP-4","MEASURE-2","MANAGE-2"],drift:{active:true,schedule:"Weekly",lastRun:"02/03/2026",nextRun:"09/03/2026",scoreDelta:0}},
  {id:"vague",title:'"AI thing to help us"',type:"demo",icon:"📋",date:"02/03/2026, 22:15",bc:T.or,desc:"Deliberately vague input — demonstrates how LaunchGuard surfaces missing context.",tags:[{l:"Low Confidence",c:"or"},{l:"Needs Detail",c:"pk"}],risks:[{id:"R1",n:"Misaligned risk analysis",s:"High",cat:"UX/Business",likelihood:"High",impact:"High"}],st:{risks:1,check:3,tests:1,guard:1,score:42},sb:[1,0,0],cl:["Specify domain and data sensitivity","Identify primary user roles","Clarify end-user vs internal"],co:["Product","Product","Product"],gtm:{h:"We need more detail.",t:"Good governance starts with clarity.",b:2,f:1},signoffs:[{role:"PM",status:"pending",user:null,at:null}],euTier:"Minimal",owasp:["LLM09"],nist:["MAP-1"],drift:{active:false}},
  {id:"trading",title:"Real-time AI Trading Advisor",type:"demo",icon:"📈",date:"02/03/2026, 21:45",bc:T.rd,desc:"High-stakes financial AI with critical risks: advice liability, data accuracy, regulatory compliance.",tags:[{l:"Critical Risks",c:"rd"},{l:"Financial",c:"pr"}],risks:[{id:"R1",n:"Personalised financial advice",s:"High",cat:"Safety",likelihood:"High",impact:"High"},{id:"R2",n:"Unsafe risk-taking encouragement",s:"High",cat:"Safety",likelihood:"Medium",impact:"High"},{id:"R3",n:"Hallucinated market data",s:"High",cat:"Safety",likelihood:"High",impact:"High"},{id:"R4",n:"User overconfidence",s:"High",cat:"UX/Business",likelihood:"High",impact:"Medium"}],st:{risks:4,check:5,tests:5,guard:4,score:55},sb:[4,0,0],cl:["Written policy on AI and securities","Advice-language guardrails tested","Red-team scenarios complete","Legal disclaimers integrated","Curated data-only mode enforced"],co:["Compliance","Engineering","QA","Legal","Engineering"],gtm:{h:"AI trading without becoming an advisor.",t:"Insights, not instructions.",b:4,f:3},signoffs:[{role:"PM",status:"approved",user:"Mark R.",at:"02/03 22:00"},{role:"Legal",status:"rejected",user:"Diana P.",at:"02/03 22:30"},{role:"QA",status:"pending",user:null,at:null},{role:"Security",status:"pending",user:null,at:null}],euTier:"High-Risk",owasp:["LLM01","LLM03","LLM06","LLM08","LLM09"],nist:["GOVERN-6","MAP-4","MEASURE-1","MANAGE-1"],drift:{active:true,schedule:"Daily",lastRun:"03/03/2026",nextRun:"04/03/2026",scoreDelta:-3}},
  {id:"prod1",title:"mart Productivity Assistant",type:"live",icon:"🤖",date:"02/03/2026, 21:34",bc:T.bl,desc:"AI-powered task management with reminders and productivity tips.",tags:[{l:"MVP",c:"bl"}],risks:[{id:"R1",n:"Data Privacy Risk",s:"High",cat:"Privacy",likelihood:"Medium",impact:"High"},{id:"R2",n:"User Confusion",s:"Medium",cat:"UX/Business",likelihood:"Medium",impact:"Medium"}],st:{risks:2,check:3,tests:2,guard:2,score:60},sb:[1,1,0],cl:["Define specific user workflows","Develop data privacy policy","Create onboarding walkthrough"],co:["Product Manager","Compliance","Product"],gtm:{h:"Your Personal Task Assistant",t:"Manage tasks, meet deadlines.",b:5,f:3},signoffs:[{role:"PM",status:"approved",user:"Othniel O.",at:"02/03 21:50"}],euTier:"Limited",owasp:["LLM06","LLM09"],nist:["MAP-2","MEASURE-2"],drift:{active:false}},
  {id:"invest",title:"AI Investment Advisor",type:"live",icon:"💰",date:"02/03/2026, 22:41",bc:T.tl,desc:"Investment recommendations with portfolio analysis.",tags:[{l:"Financial",c:"pr"}],risks:[{id:"R1",n:"Unsuitable investment recommendations",s:"High",cat:"Safety",likelihood:"Medium",impact:"High"},{id:"R2",n:"Stale market data",s:"High",cat:"Safety",likelihood:"Medium",impact:"High"},{id:"R3",n:"Regulatory non-compliance",s:"High",cat:"Privacy",likelihood:"Low",impact:"High"}],st:{risks:3,check:4,tests:3,guard:3,score:62},sb:[3,0,0],cl:["Regulatory review complete","Suitability guardrails tested","Real-time data feed validated","Disclaimers on all outputs"],co:["Compliance","Engineering","Engineering","Legal"],gtm:{h:"Smarter investing, governed by design.",t:"Data-driven with compliance.",b:3,f:2},signoffs:[{role:"PM",status:"approved",user:"Othniel O.",at:"02/03 23:00"},{role:"Legal",status:"pending",user:null,at:null},{role:"QA",status:"pending",user:null,at:null}],euTier:"High-Risk",owasp:["LLM01","LLM03","LLM06","LLM08"],nist:["GOVERN-6","MAP-4","MEASURE-1","MANAGE-1","MANAGE-4"],drift:{active:true,schedule:"Daily",lastRun:"03/03/2026",nextRun:"04/03/2026",scoreDelta:-1}},
];

const AUDIT_LOG=[{time:"02 Mar 22:48",email:"admin@launchguard.dev",status:"success",reason:"login",ip:"10.17.106.64",ua:"Mozilla/5.0..."},{time:"02 Mar 22:39",email:"admin@launchguard.dev",status:"success",reason:"login",ip:"10.17.106.64",ua:"Mozilla/5.0..."},{time:"02 Mar 22:31",email:"heatmap_test@test.dev",status:"success",reason:"login",ip:"127.0.0.1",ua:"curl/8.5.0"},{time:"02 Mar 22:30",email:"heatmap_test@test.dev",status:"success",reason:"signup",ip:"127.0.0.1",ua:"curl/8.5.0"},{time:"02 Mar 21:35",email:"peprodev@gmail.com",status:"failed",reason:"bad_credentials",ip:"10.17.106.64",ua:"Mozilla/5.0..."},{time:"02 Mar 21:35",email:"peprodev@gmail.com",status:"failed",reason:"bad_credentials",ip:"10.17.106.64",ua:"Mozilla/5.0..."},{time:"28 Feb 21:23",email:"admin@launchguard.dev",status:"success",reason:"login",ip:"10.17.106.64",ua:"Mozilla/5.0..."},{time:"28 Feb 21:22",email:"peprodev@gmail.com",status:"failed",reason:"bad_credentials",ip:"10.17.106.64",ua:"Mozilla/5.0..."},{time:"28 Feb 08:22",email:"test@example.com",status:"success",reason:"signup",ip:"127.0.0.1",ua:"python-requests/2.32.3"},{time:"28 Feb 08:22",email:"admin@launchguard.dev",status:"failed",reason:"admin_bad_credentials",ip:"127.0.0.1",ua:"python-requests/2.32.3"}];

const REG_FRAMEWORKS=[
  {id:"euai",name:"EU AI Act",version:"2024/1689",jurisdiction:"EU",reqs:87,status:"Active",articles:["Art. 5 — Prohibited practices","Art. 6 — High-risk classification","Art. 9 — Risk management system","Art. 10 — Data governance","Art. 13 — Transparency","Art. 14 — Human oversight","Art. 15 — Accuracy & robustness","Art. 50 — Transparency (limited risk)"]},
  {id:"owasp",name:"OWASP Top 10 LLM",version:"2025 v2.0",jurisdiction:"Global",reqs:47,status:"Active",articles:["LLM01 — Prompt Injection","LLM02 — Insecure Output","LLM03 — Training Data Poisoning","LLM04 — Model DoS","LLM05 — Supply Chain","LLM06 — Sensitive Info Disclosure","LLM07 — Insecure Plugin","LLM08 — Excessive Agency","LLM09 — Overreliance","LLM10 — Model Theft"]},
  {id:"nist",name:"NIST AI RMF",version:"v1.0",jurisdiction:"US",reqs:72,status:"Active",articles:["GOVERN — Policies & accountability","MAP — Context & stakeholder impact","MEASURE — Risk assessment","MANAGE — Risk treatment & monitoring"]},
  {id:"iso",name:"ISO/IEC 42001",version:"2023",jurisdiction:"International",reqs:39,status:"Active",articles:["Annex A — AI management controls"]},
  {id:"gdpr",name:"GDPR (AI articles)",version:"2016/679",jurisdiction:"EU",reqs:12,status:"Active",articles:["Art. 22 — Automated decision-making","Art. 25 — Data protection by design","Art. 35 — DPIA"]},
  {id:"soc2",name:"SOC 2 Type II",version:"2022",jurisdiction:"US",reqs:23,status:"Active",articles:["CC6 — Logical access","CC7 — Change management","PI1 — Processing integrity"]},
  {id:"hipaa",name:"HIPAA",version:"2013 + AI",jurisdiction:"US",reqs:18,status:"Active",articles:["164.312 — Technical safeguards","164.502 — Minimum necessary"]},
];

const GATE_CONFIG={name:"Production Gate",type:"CI/CD",minScore:65,requiredSignoffs:["PM","Legal","QA"],requiredFrameworks:["EU AI Act","OWASP"],active:true};

// ═══ PAGES ═══

// ── Landing ──
function Landing({onLogin}){return <div style={{maxWidth:700,margin:"0 auto"}}><div className="fu" style={{textAlign:"center",padding:"56px 0 28px"}}><Bdg c="pr" sz="lg" s={{letterSpacing:1.5}}>✦ RELEASE READINESS COPILOT</Bdg><h1 style={{fontSize:42,fontWeight:800,color:T.tx,marginTop:20,lineHeight:1.1,letterSpacing:-.8}}>Is your AI feature<br/>actually ready to ship?</h1><p style={{fontSize:15,color:T.tx2,marginTop:16,lineHeight:1.7,maxWidth:500,margin:"16px auto 0"}}>Three agents + live regulation engine. Maps risks to EU AI Act, OWASP, NIST, ISO 42001, GDPR, SOC 2 and HIPAA in real time.</p><div style={{display:"flex",justifyContent:"center",gap:10,marginTop:28}}>{[{v:"3",l:"AGENTS"},{v:"<60s",l:"PIPELINE"},{v:"7",l:"FRAMEWORKS"},{v:"0",l:"MANUAL DOCS"}].map((s,i)=><div key={i} className={`fu s${i+1}`} style={{background:T.sf,border:`1px solid ${T.bd}`,borderRadius:8,padding:"14px 18px",textAlign:"center"}}><div style={{fontSize:20,fontWeight:800,color:T.tx}}>{s.v}</div><div style={{fontSize:8,color:T.tx4,letterSpacing:1.4,marginTop:3,fontWeight:600}}>{s.l}</div></div>)}</div></div>
<div className="fu s3" style={{marginTop:48}}><h2 style={{fontSize:18,fontWeight:700,color:T.tx,marginBottom:16}}>🛡 Live Regulation Engine</h2><div style={{display:"grid",gridTemplateColumns:"repeat(4,1fr)",gap:8}}>{REG_FRAMEWORKS.slice(0,4).map((f,i)=><Crd key={i} style={{padding:12,borderTop:`2px solid ${T.pr}`}}><div style={{fontSize:12,fontWeight:700,color:T.tx}}>{f.name}</div><div style={{fontSize:10,color:T.tx3,marginTop:2}}>{f.reqs} requirements</div><Bdg c="gn" sz="xs" s={{marginTop:6}}>{f.status}</Bdg></Crd>)}</div></div>
<div className="fu s4" style={{marginTop:32}}><h2 style={{fontSize:18,fontWeight:700,color:T.tx,marginBottom:16}}>⚡ Enforceable Governance</h2><div style={{display:"grid",gridTemplateColumns:"repeat(3,1fr)",gap:8}}>{[{t:"CI/CD Gates",d:"Block releases below score threshold",i:"🚦"},{t:"Role Sign-offs",d:"PM, Legal, QA, Security must approve",i:"✍️"},{t:"Compliance Certs",d:"Auditor-ready PDF with signatures",i:"📜"},{t:"Drift Monitor",d:"Re-scan deployed features weekly",i:"📡"},{t:"Risk Trends",d:"Track posture across all features",i:"📊"},{t:"Session Compare",d:"v1 vs v2 side-by-side diff",i:"⚡"}].map((f,i)=><Crd key={i} style={{padding:12}}><div style={{fontSize:16}}>{f.i}</div><div style={{fontSize:12,fontWeight:700,color:T.tx,marginTop:4}}>{f.t}</div><div style={{fontSize:10,color:T.tx3,marginTop:2}}>{f.d}</div></Crd>)}</div></div>
<div className="fu s5" style={{textAlign:"center",padding:"48px 0 28px"}}><div style={{fontSize:22,fontWeight:800,color:T.tx}}>Ready to run your first check?</div><p style={{fontSize:13,color:T.tx3,marginTop:6}}>No setup required. Three agents + seven regulatory frameworks.</p><Btn v="cta" sz="lg" onClick={onLogin} s={{marginTop:16}}>✦ Try It Now</Btn></div></div>;}

// ── Dashboard ──
function Dashboard({onNew,onOpen}){
  const scores=S_DATA.map(s=>s.st.score);const avg=Math.round(scores.reduce((a,b)=>a+b,0)/scores.length);
  const driftAlerts=S_DATA.filter(s=>s.drift?.scoreDelta<0).length;
  const pendingSignoffs=S_DATA.reduce((a,s)=>a+s.signoffs.filter(x=>x.status==="pending").length,0);
  return <div style={{maxWidth:960,margin:"0 auto"}}><div className="fu" style={{display:"flex",justifyContent:"space-between",alignItems:"center",marginBottom:20,paddingTop:24}}><div><h1 style={{fontSize:24,fontWeight:800,color:T.tx}}>Dashboard</h1><p style={{fontSize:13,color:T.tx3,marginTop:2}}>Release readiness overview</p></div><Btn v="primary" sz="sm" onClick={onNew}>+ New Readiness Check</Btn></div>
  <div className="fu s1" style={{display:"grid",gridTemplateColumns:"repeat(6,1fr)",gap:10,marginBottom:16}}>{[{l:"Sessions",v:S_DATA.length,c:T.bl},{l:"Avg Score",v:avg,c:avg>=60?T.or:T.rd},{l:"Total Risks",v:S_DATA.reduce((a,s)=>a+s.st.risks,0),c:T.or},{l:"Pending Sign-offs",v:pendingSignoffs,c:pendingSignoffs>0?T.rd:T.gn},{l:"Drift Alerts",v:driftAlerts,c:driftAlerts>0?T.rd:T.gn},{l:"Frameworks",v:REG_FRAMEWORKS.length,c:T.pr}].map((x,i)=><Crd key={i} style={{textAlign:"center",padding:12}}><div style={{fontSize:24,fontWeight:800,color:x.c}}>{x.v}</div><div style={{fontSize:9,color:T.tx4,marginTop:2}}>{x.l}</div></Crd>)}</div>

  {/* Risk Trend Chart */}
  <Crd className="fu s2" style={{marginBottom:16}}><Lbl>📊 Readiness Score Trends</Lbl><svg viewBox="0 0 500 70" style={{width:"100%",height:80}}>{[0,1,2].map(i=><line key={i} x1="0" y1={i*30+5} x2="500" y2={i*30+5} stroke={T.bd} strokeWidth=".4" strokeDasharray="3"/>)}<polyline points={S_DATA.map((s,i)=>`${i*(500/Math.max(S_DATA.length-1,1))},${70-((s.st.score-30)/50)*65}`).join(" ")} fill="none" stroke={T.bl} strokeWidth="2" strokeLinejoin="round"/>{S_DATA.map((s,i)=><circle key={i} cx={i*(500/Math.max(S_DATA.length-1,1))} cy={70-((s.st.score-30)/50)*65} r="4" fill={s.st.score>=65?T.gn:T.or} stroke={T.sf} strokeWidth="2"/>)}</svg></Crd>

  {/* Two columns */}
  <div style={{display:"grid",gridTemplateColumns:"1fr 1fr",gap:14}}>
  <div><Lbl>Recent Sessions</Lbl>{S_DATA.slice(0,4).map(s=><Crd key={s.id} onClick={()=>onOpen(s.id)} style={{marginBottom:8,padding:12}}><div style={{display:"flex",justifyContent:"space-between",alignItems:"center"}}><div style={{display:"flex",alignItems:"center",gap:8}}><span style={{fontSize:16}}>{s.icon}</span><div><div style={{fontSize:12,fontWeight:600,color:T.tx}}>{s.title}</div><div style={{fontSize:10,color:T.tx4,fontFamily:M}}>{s.date.split(",")[0]}</div></div></div><CS score={s.st.score} sz={36}/></div></Crd>)}</div>
  <div><Lbl>Governance Status</Lbl>
  {/* Gate config */}
  <Crd style={{marginBottom:8,padding:12,borderLeft:`3px solid ${T.pr}`}}><div style={{fontSize:12,fontWeight:700,color:T.tx}}>🚦 {GATE_CONFIG.name}</div><div style={{fontSize:10,color:T.tx3,marginTop:3}}>Min score: {GATE_CONFIG.minScore} · Sign-offs: {GATE_CONFIG.requiredSignoffs.join(", ")}</div><div style={{display:"flex",gap:4,marginTop:6}}>{GATE_CONFIG.requiredFrameworks.map((f,i)=><Bdg key={i} c="pr" sz="xs">{f}</Bdg>)}</div></Crd>
  {/* Drift alerts */}
  <Crd style={{marginBottom:8,padding:12,borderLeft:`3px solid ${driftAlerts>0?T.rd:T.gn}`}}><div style={{fontSize:12,fontWeight:700,color:T.tx}}>📡 Drift Monitor</div><div style={{fontSize:10,color:T.tx3,marginTop:3}}>{S_DATA.filter(s=>s.drift?.active).length} active monitors · {driftAlerts} regressions detected</div>{S_DATA.filter(s=>s.drift?.scoreDelta<0).map(s=><div key={s.id} style={{fontSize:10,color:T.rd2,marginTop:4}}>⚠ {s.title}: {s.drift.scoreDelta} points</div>)}</Crd>
  {/* Pending sign-offs */}
  <Crd style={{padding:12,borderLeft:`3px solid ${pendingSignoffs>0?T.or:T.gn}`}}><div style={{fontSize:12,fontWeight:700,color:T.tx}}>✍️ Pending Sign-offs</div>{S_DATA.filter(s=>s.signoffs.some(x=>x.status==="pending")).slice(0,3).map(s=><div key={s.id} style={{fontSize:10,color:T.or2,marginTop:4}}>{s.title}: {s.signoffs.filter(x=>x.status==="pending").map(x=>x.role).join(", ")}</div>)}</Crd>
  </div></div></div>;
}

// ── Sessions List ──
function SessionsList({onOpen,onNew,onCompare}){
  const[filter,setF]=useState("all");const[compareMode,setCM]=useState(false);const[sel,setSel]=useState([]);
  const filtered=filter==="all"?S_DATA:S_DATA.filter(s=>s.type===filter);
  const toggleSel=(id)=>{if(sel.includes(id))setSel(sel.filter(x=>x!==id));else if(sel.length<2)setSel([...sel,id]);};
  return <div style={{maxWidth:960,margin:"0 auto"}}><div className="fu" style={{display:"flex",justifyContent:"space-between",alignItems:"center",paddingTop:24,marginBottom:16}}><div><h1 style={{fontSize:24,fontWeight:800,color:T.tx}}>Sessions</h1><p style={{fontSize:13,color:T.tx3,marginTop:2}}>{S_DATA.length} checks</p></div><div style={{display:"flex",gap:6}}>{compareMode&&sel.length===2&&<Btn v="primary" sz="sm" onClick={()=>{onCompare(sel[0],sel[1]);setCM(false);setSel([])}}>Compare Selected</Btn>}<Btn v={compareMode?"danger":"ghost"} sz="sm" onClick={()=>{setCM(!compareMode);setSel([])}}>{compareMode?"Cancel":"⚡ Compare"}</Btn><Btn v="primary" sz="sm" onClick={onNew}>+ New Check</Btn></div></div>
  <div className="fu s1" style={{display:"flex",gap:4,marginBottom:12}}>{[{k:"all",l:"All"},{k:"live",l:"Live"},{k:"demo",l:"Demos"}].map(f=><Btn key={f.k} v={filter===f.k?"primary":"ghost"} sz="xs" onClick={()=>setF(f.k)}>{f.l}</Btn>)}</div>
  <div style={{border:`1px solid ${T.bd}`,borderRadius:10,overflow:"hidden"}}><div style={{display:"grid",gridTemplateColumns:compareMode?"30px 2fr 70px 50px 50px 50px 70px 60px":"2fr 70px 50px 50px 50px 70px 60px",padding:"8px 14px",background:T.sf2,borderBottom:`1px solid ${T.bd}`}}>{compareMode&&<div/>}{["Session","Score","Risks","Tests","Guards","Date","Type"].map(h=><div key={h} style={{fontSize:9,fontWeight:700,color:T.tx4,letterSpacing:.5}}>{h}</div>)}</div>
  {filtered.map((s,i)=><div key={s.id} className={`fu s${Math.min(i+1,6)}`} onClick={()=>compareMode?toggleSel(s.id):onOpen(s.id)} style={{display:"grid",gridTemplateColumns:compareMode?"30px 2fr 70px 50px 50px 50px 70px 60px":"2fr 70px 50px 50px 50px 70px 60px",padding:"10px 14px",borderBottom:i<filtered.length-1?`1px solid ${T.bd}`:"none",cursor:"pointer",background:sel.includes(s.id)?T.prA:"transparent"}} onMouseEnter={e=>{if(!sel.includes(s.id))e.currentTarget.style.background=T.sf2}} onMouseLeave={e=>{if(!sel.includes(s.id))e.currentTarget.style.background="transparent"}}>
    {compareMode&&<div style={{display:"flex",alignItems:"center"}}><div style={{width:14,height:14,borderRadius:3,border:`2px solid ${sel.includes(s.id)?T.pr:T.bd2}`,background:sel.includes(s.id)?T.pr:"transparent",display:"flex",alignItems:"center",justifyContent:"center",fontSize:9,color:"#fff"}}>{sel.includes(s.id)&&"✓"}</div></div>}
    <div style={{display:"flex",alignItems:"center",gap:6}}><span style={{fontSize:14}}>{s.icon}</span><div><div style={{fontSize:12,fontWeight:600,color:T.tx}}>{s.title}</div><div style={{fontSize:9,color:T.tx4}}>{s.desc.slice(0,50)}...</div></div></div>
    <div style={{display:"flex",alignItems:"center"}}><CS score={s.st.score} sz={30}/></div>
    <div style={{display:"flex",alignItems:"center",fontSize:12,fontWeight:600,color:T.or}}>{s.st.risks}</div>
    <div style={{display:"flex",alignItems:"center",fontSize:12,fontWeight:600,color:T.tl}}>{s.st.tests}</div>
    <div style={{display:"flex",alignItems:"center",fontSize:12,fontWeight:600,color:T.pr2}}>{s.st.guard}</div>
    <div style={{display:"flex",alignItems:"center",fontSize:10,color:T.tx3,fontFamily:M}}>{s.date.split(",")[0]}</div>
    <div style={{display:"flex",alignItems:"center"}}><Bdg c={s.type==="demo"?"or":"bl"} sz="xs">{s.type}</Bdg></div>
  </div>)}</div></div>;
}

// ── Session Detail ──
function SessionDetail({session:s,onBack}){
  const[tab,sTab]=useState("overview");const st=s.st;
  return <div style={{maxWidth:960,margin:"0 auto"}}>
  <div className="fu" style={{display:"flex",justifyContent:"space-between",alignItems:"center",flexWrap:"wrap",gap:8,paddingTop:16,marginBottom:4}}><div style={{display:"flex",alignItems:"center",gap:8}}><Btn v="ghost" sz="xs" onClick={onBack}>← Back</Btn><span style={{fontSize:20}}>{s.icon}</span><div><div style={{fontSize:16,fontWeight:700,color:T.tx,display:"flex",alignItems:"center",gap:6}}>{s.title}<Bdg c={s.type==="demo"?"or":"bl"} sz="xs">{s.type}</Bdg><Bdg c={s.euTier==="High-Risk"?"rd":s.euTier==="Limited"?"or":"gn"} sz="xs">EU: {s.euTier}</Bdg></div><div style={{fontSize:10,color:T.tx4,fontFamily:M}}>{s.date}</div></div></div>
  <div style={{display:"flex",gap:4,flexWrap:"wrap"}}>{[{l:"🔌 Integrations",v:"ghost"},{l:"🔄 Re-analyze",v:"danger"},{l:"🔗 Share",v:"ghost"},{l:"⬇ Package",v:"success"},{l:"📄 PDF",v:"ghost"},{l:"✉ Email",v:"ghost"},{l:"📜 Certificate",v:"primary"}].map((b,i)=><Btn key={i} v={b.v} sz="xs">{b.l}</Btn>)}<Bdg c="gn">✓ COMPLETE</Bdg></div></div>
  <Pipeline phase={3}/>
  <div className="fu s1" style={{background:T.orA,border:`1px solid ${T.or}20`,borderRadius:6,padding:"6px 12px",margin:"6px 0 12px",fontSize:11,color:T.or2}}>⚠ AI-generated — requires human review before production use.</div>

  {/* Tabs — now 6 */}
  <div style={{display:"flex",gap:0,marginBottom:16,borderBottom:`1px solid ${T.bd}`,overflowX:"auto"}}>{[{k:"overview",l:"Overview"},{k:"spec",l:"Spec & Risks"},{k:"tests",l:"Tests & Guardrails"},{k:"docs",l:"Docs & Launch"},{k:"regulation",l:"Regulation"},{k:"governance",l:"Governance"}].map(t=><button key={t.k} onClick={()=>sTab(t.k)} style={{background:"transparent",border:"none",color:tab===t.k?T.tx:T.tx4,fontSize:12,fontWeight:tab===t.k?600:400,padding:"8px 14px",cursor:"pointer",borderBottom:tab===t.k?`2px solid ${T.pr2}`:"2px solid transparent",fontFamily:F,whiteSpace:"nowrap"}}>{t.l}</button>)}</div>

  {/* OVERVIEW */}
  {tab==="overview"&&<div>
    <Crd className="fu" style={{marginBottom:12}}><div style={{display:"flex",justifyContent:"space-between"}}><div style={{display:"flex",alignItems:"center",gap:6}}><span>🏆</span><span style={{fontSize:14,fontWeight:700,color:T.tx}}>Readiness Score</span></div><span style={{fontSize:10,color:T.tx4}}>Risk coverage, spec, tests, guardrails, checklist</span></div>
    <div style={{display:"flex",alignItems:"center",gap:28,marginTop:14}}><div style={{textAlign:"center",flexShrink:0}}><CS score={st.score} sz={90}/><div style={{fontSize:10,color:T.tx4,marginTop:2}}>/ 100</div></div><div style={{flex:1,display:"flex",flexDirection:"column",gap:6}}>{[{l:"Risk Coverage",p:100,c:T.gn},{l:"Spec Completeness",p:100,c:T.gn},{l:"Test Coverage",p:Math.round(st.tests/Math.max(st.risks,1)*25),c:T.rd},{l:"Guardrails",p:Math.round(st.guard/Math.max(st.risks,1)*25),c:T.rd},{l:"Checklist",p:Math.round(st.check/10*20),c:T.rd}].map((b,i)=><div key={i} style={{display:"flex",alignItems:"center",gap:8}}><span style={{fontSize:10,color:T.tx2,width:100,flexShrink:0}}>{b.l}</span><PB pct={b.p} color={b.c}/><span style={{fontSize:10,color:b.c,fontWeight:600,width:30,textAlign:"right"}}>{b.p}%</span></div>)}</div></div></Crd>

    <div style={{display:"grid",gridTemplateColumns:"repeat(4,1fr)",gap:10,marginBottom:12}}>{[{i:"⚠️",v:st.risks,l:"Risks",c:T.or},{i:"✅",v:st.check,l:"Checklist",c:T.gn},{i:"✏️",v:st.tests,l:"Tests",c:T.tl},{i:"🛡",v:st.guard,l:"Guardrails",c:T.pr2}].map((x,i)=><Crd key={i} className={`fu s${i+1}`} style={{textAlign:"center",padding:12}}><div style={{fontSize:14}}>{x.i}</div><div style={{fontSize:24,fontWeight:800,color:x.c}}>{x.v}</div><div style={{fontSize:9,color:T.tx4}}>{x.l}</div></Crd>)}</div>

    <Crd className="fu s3" style={{marginBottom:12}}><Lbl>Risk Severity</Lbl><div style={{display:"flex",gap:5,marginBottom:8}}><Bdg c="rd" sz="xs">{s.sb[0]} High</Bdg><Bdg c="or" sz="xs">{s.sb[1]} Medium</Bdg><Bdg c="gn" sz="xs">{s.sb[2]} Low</Bdg></div>{s.risks.map((r,i)=><div key={i} style={{display:"flex",justifyContent:"space-between",alignItems:"center",padding:"8px 0",borderTop:`1px solid ${T.bd}`}}><span style={{fontSize:12,color:T.tx}}><span style={{color:T.tx4,marginRight:8,fontFamily:M,fontSize:10}}>{r.id}</span>{r.n}</span><div style={{display:"flex",gap:4}}><Bdg c={r.s==="High"?"rd":"or"} sz="xs">{r.s}</Bdg><Bdg c="bl" sz="xs">{r.cat}</Bdg></div></div>)}</Crd>

    <Crd className="fu s4" style={{marginBottom:12}}><Lbl>Must-Do Before Launch</Lbl>{s.cl.map((c,i)=><div key={i} style={{display:"flex",alignItems:"center",gap:8,padding:"7px 0",borderTop:i?`1px solid ${T.bd}`:"none"}}><div style={{width:13,height:13,borderRadius:3,border:`1.5px solid ${T.bd2}`,flexShrink:0}}/><span style={{flex:1,fontSize:11,color:T.tx2,lineHeight:1.4}}>{c}</span><Bdg c="rd" sz="xs">Must</Bdg><span style={{fontSize:9,color:T.tx4,fontFamily:M}}>{s.co[i]}</span></div>)}</Crd>

    <Crd className="fu s5"><Lbl>📣 GTM Preview</Lbl><div style={{background:T.sf2,borderRadius:7,padding:12}}><div style={{fontSize:13,fontWeight:700,color:T.rd2}}>{s.gtm.h}</div><div style={{fontSize:11,color:T.tx4,marginTop:2,fontStyle:"italic"}}>{s.gtm.t}</div><div style={{display:"flex",gap:4,marginTop:8}}><Bdg c="bl" sz="xs">✦ {s.gtm.b} Benefits</Bdg><Bdg c="tl" sz="xs">◎ {s.gtm.f} Features</Bdg><Bdg c="or" sz="xs">🔒 Trust</Bdg></div></div></Crd>
  </div>}

  {/* SPEC & RISKS */}
  {tab==="spec"&&<div>
    <div className="fu" style={{display:"flex",alignItems:"center",gap:8,padding:"10px 14px",background:T.sf2,border:`1px solid ${T.bd}`,borderRadius:8,marginBottom:14}}><span style={{fontSize:12,color:T.tx2,fontWeight:600}}>📋 Compliance:</span>{["GDPR","SOC2","HIPAA"].map(c=><button key={c} style={{background:T.sf3,border:`1px solid ${T.bd}`,borderRadius:5,padding:"4px 10px",fontSize:11,fontWeight:600,color:T.tx,cursor:"pointer",fontFamily:F}}>{c}</button>)}<span style={{fontSize:10,color:T.tx4}}>Add compliance checklist items</span></div>
    <Crd className="fu s1" style={{marginBottom:14}}><Lbl>📊 Risk Heatmap — {s.risks.length} total: {s.sb[0]} High · {s.sb[1]} Medium · {s.sb[2]} Low</Lbl><Heatmap risks={s.risks}/></Crd>
    <Crd className="fu s2" style={{marginBottom:14}}><Lbl>📋 Release Spec</Lbl><div style={{fontSize:12,color:T.tx2,lineHeight:1.6}}><strong style={{color:T.tx}}>Problem:</strong> {s.desc}</div></Crd>
    <Crd className="fu s3" style={{marginBottom:14}}><div style={{display:"flex",justifyContent:"space-between",marginBottom:10}}><Lbl>⚠️ Risk Register</Lbl><Btn v="ghost" sz="xs">📋 Copy Markdown</Btn></div><div style={{display:"grid",gridTemplateColumns:"35px 1fr 80px 70px 65px 65px 55px",padding:"6px 0",borderBottom:`1px solid ${T.bd}`}}>{["ID","TITLE","CATEGORY","LIKELIHOOD","IMPACT","SEVERITY","TEST"].map(h=><div key={h} style={{fontSize:8,fontWeight:700,color:T.tx4,letterSpacing:.6}}>{h}</div>)}</div>{s.risks.map((r,i)=><div key={i} style={{display:"grid",gridTemplateColumns:"35px 1fr 80px 70px 65px 65px 55px",padding:"8px 0",borderBottom:`1px solid ${T.bd}`}}><div style={{fontSize:11,color:T.tx3,fontFamily:M}}>{r.id}</div><div style={{fontSize:11,fontWeight:600,color:T.tx}}>{r.n}</div><div><Bdg c={r.cat==="Privacy"?"pk":r.cat==="Safety"?"rd":"bl"} sz="xs">{r.cat}</Bdg></div><div style={{fontSize:11,color:T.tx2}}>{r.likelihood||"Medium"}</div><div style={{fontSize:11,color:T.tx2}}>{r.impact||"High"}</div><div><Bdg c={r.s==="High"?"rd":"or"} sz="xs">{r.s}</Bdg></div><div><Bdg c="tl" sz="xs">T{i+1}</Bdg></div></div>)}</Crd>
    <Crd className="fu s4"><Lbl>✅ Readiness Checklist</Lbl>{s.cl.map((c,i)=><div key={i} style={{display:"flex",alignItems:"center",gap:8,padding:"7px 0",borderBottom:`1px solid ${T.bd}`}}><div style={{width:13,height:13,borderRadius:3,border:`1.5px solid ${T.bd2}`,flexShrink:0}}/><span style={{flex:1,fontSize:11,color:T.tx2}}>{c}</span><Bdg c="rd" sz="xs">Must</Bdg><span style={{fontSize:9,color:T.tx4,fontFamily:M}}>{s.co[i]}</span></div>)}</Crd>
  </div>}

  {/* TESTS */}
  {tab==="tests"&&<div>
    <Crd className="fu" style={{marginBottom:14}}><Lbl>✏️ Test Cases</Lbl>{Array.from({length:st.tests},(_,i)=><div key={i} style={{padding:8,background:T.sf2,borderRadius:7,marginBottom:4}}><div style={{fontSize:11,fontWeight:600,color:T.tx}}>TC-{i+1}: {s.risks[i%s.risks.length].n}</div><div style={{display:"flex",gap:4,marginTop:4}}><Bdg c="pr" sz="xs">Unit → AI Eval</Bdg><Bdg c="tl" sz="xs">→ {s.risks[i%s.risks.length].id}</Bdg></div></div>)}</Crd>
    <Crd className="fu s1"><Lbl>🛡 Guardrails</Lbl>{["PreProcessing validation","ModelCall constraints","PostProcessing filtering","UI disclaimers","AccessControl restrictions"].slice(0,st.guard).map((g,i)=><div key={i} style={{padding:8,background:T.sf2,borderRadius:7,marginBottom:4}}><div style={{fontSize:11,fontWeight:600,color:T.tx}}>G-{i+1}: {g}</div><Bdg c="gn" sz="xs" s={{marginTop:4}}>Implementation guidance</Bdg></div>)}</Crd>
  </div>}

  {/* DOCS */}
  {tab==="docs"&&<div>
    <Crd className="fu" style={{marginBottom:14}}><Lbl>📝 Release Notes</Lbl><div style={{padding:12,background:T.sf2,borderRadius:7,fontSize:12,color:T.tx2,lineHeight:1.6}}><strong style={{color:T.pr2}}>v1.0 — {s.title}</strong><br/><br/><strong style={{color:T.tx}}>What's New:</strong> {s.desc}<br/><br/><strong style={{color:T.tx}}>Limitations:</strong> All outputs require human review.</div></Crd>
    <Crd className="fu s1" style={{marginBottom:14}}><Lbl>🌐 GTM Landing Page</Lbl><div style={{padding:16,background:T.sf2,borderRadius:7,textAlign:"center"}}><div style={{fontSize:16,fontWeight:800,color:T.tx}}>{s.gtm.h}</div><div style={{fontSize:11,color:T.tx4,marginTop:3,fontStyle:"italic"}}>{s.gtm.t}</div></div></Crd>
    <Crd className="fu s2"><Lbl>📊 Pitch Deck</Lbl><div style={{fontSize:12,color:T.tx2}}>7-slide outline: Problem → Solution → Architecture → Risk Mitigation → GTM → Roadmap → Ask</div></Crd>
  </div>}

  {/* REGULATION — NEW */}
  {tab==="regulation"&&<div>
    <Crd className="fu" style={{marginBottom:14}}><Lbl>🏛 EU AI Act Classification</Lbl><div style={{display:"flex",alignItems:"center",gap:12}}><div style={{padding:"12px 20px",background:s.euTier==="High-Risk"?T.rdA:s.euTier==="Limited"?T.orA:T.gnA,border:`1px solid ${s.euTier==="High-Risk"?T.rd:s.euTier==="Limited"?T.or:T.gn}30`,borderRadius:8,textAlign:"center"}}><div style={{fontSize:18,fontWeight:800,color:s.euTier==="High-Risk"?T.rd:s.euTier==="Limited"?T.or:T.gn}}>{s.euTier}</div><div style={{fontSize:9,color:T.tx4,marginTop:2}}>EU AI Act Risk Tier</div></div><div style={{flex:1,fontSize:12,color:T.tx2,lineHeight:1.6}}>{s.euTier==="High-Risk"?"Full conformity assessment required. Risk management system (Art. 9), data governance (Art. 10), transparency (Art. 13), human oversight (Art. 14), and accuracy/robustness (Art. 15) all apply.":s.euTier==="Limited"?"Transparency obligations apply (Art. 50). Users must be informed they are interacting with AI.":"Standard analysis with best-practice recommendations."}</div></div></Crd>

    <Crd className="fu s1" style={{marginBottom:14}}><Lbl>🔐 OWASP Top 10 LLM — Triggered Vulnerabilities</Lbl>{s.owasp.map((id,i)=>{const vul=REG_FRAMEWORKS.find(f=>f.id==="owasp").articles.find(a=>a.startsWith(id));return <div key={i} style={{padding:8,background:T.sf2,borderRadius:7,marginBottom:4,display:"flex",justifyContent:"space-between",alignItems:"center"}}><div><div style={{fontSize:11,fontWeight:600,color:T.tx}}>{vul}</div></div><Bdg c="rd" sz="xs">Triggered</Bdg></div>;})}</Crd>

    <Crd className="fu s2" style={{marginBottom:14}}><Lbl>📋 NIST AI RMF Mapping</Lbl>{s.nist.map((id,i)=><div key={i} style={{padding:8,background:T.sf2,borderRadius:7,marginBottom:4}}><div style={{fontSize:11,fontWeight:600,color:T.tx}}>{id}: {id.startsWith("GOVERN")?"Policies & accountability":id.startsWith("MAP")?"Context & stakeholder impact":id.startsWith("MEASURE")?"Risk assessment":"Risk treatment & monitoring"}</div><Bdg c="gn" sz="xs" s={{marginTop:4}}>Mapped</Bdg></div>)}</Crd>

    <Crd className="fu s3"><Lbl>📊 All Frameworks — Compliance Summary</Lbl><div style={{display:"grid",gridTemplateColumns:"repeat(4,1fr)",gap:8}}>{REG_FRAMEWORKS.slice(0,4).map((f,i)=><div key={i} style={{padding:10,background:T.sf2,borderRadius:7,textAlign:"center"}}><div style={{fontSize:11,fontWeight:700,color:T.tx}}>{f.name}</div><div style={{fontSize:9,color:T.tx3,marginTop:2}}>{f.reqs} requirements</div><div style={{marginTop:6}}><PB pct={s.euTier==="High-Risk"?35:s.euTier==="Limited"?60:80} color={s.euTier==="High-Risk"?T.rd:T.or}/></div><div style={{fontSize:9,color:T.tx4,marginTop:3}}>{s.euTier==="High-Risk"?"12 gaps":"3 gaps"}</div></div>)}</div></Crd>
  </div>}

  {/* GOVERNANCE — NEW */}
  {tab==="governance"&&<div>
    <Crd className="fu" style={{marginBottom:14}}><Lbl>✍️ Role-Based Sign-offs</Lbl><div style={{display:"grid",gridTemplateColumns:"repeat(2,1fr)",gap:8}}>{s.signoffs.map((so,i)=><div key={i} style={{padding:10,background:T.sf2,borderRadius:7,border:`1px solid ${so.status==="approved"?T.gn:so.status==="rejected"?T.rd:T.or}25`}}><div style={{display:"flex",justifyContent:"space-between",alignItems:"center"}}><div style={{fontSize:12,fontWeight:700,color:T.tx}}>{so.role}</div><Bdg c={so.status==="approved"?"gn":so.status==="rejected"?"rd":"or"} sz="xs">{so.status==="approved"?"✓ Approved":so.status==="rejected"?"✕ Rejected":"⏳ Pending"}</Bdg></div>{so.user&&<div style={{fontSize:10,color:T.tx3,marginTop:4}}>{so.user} · {so.at}</div>}{so.status==="pending"&&<Btn v="primary" sz="xs" s={{marginTop:8,width:"100%"}}>Sign Off</Btn>}</div>)}</div></Crd>

    <Crd className="fu s1" style={{marginBottom:14}}><Lbl>🚦 Gate Evaluation</Lbl>{(()=>{const passed=st.score>=GATE_CONFIG.minScore;const signoffsMet=GATE_CONFIG.requiredSignoffs.every(r=>s.signoffs.find(so=>so.role===r&&so.status==="approved"));const allPassed=passed&&signoffsMet;return <div><div style={{display:"flex",alignItems:"center",gap:10,marginBottom:10}}><div style={{padding:"10px 16px",background:allPassed?T.gnA:T.rdA,border:`1px solid ${allPassed?T.gn:T.rd}30`,borderRadius:8}}><div style={{fontSize:16,fontWeight:800,color:allPassed?T.gn:T.rd}}>{allPassed?"PASS":"FAIL"}</div></div><div><div style={{fontSize:12,color:T.tx}}>Score: {st.score}/{GATE_CONFIG.minScore} required — <span style={{color:passed?T.gn:T.rd}}>{passed?"✓ Met":"✕ Below"}</span></div><div style={{fontSize:12,color:T.tx,marginTop:2}}>Sign-offs: {GATE_CONFIG.requiredSignoffs.map(r=>{const so=s.signoffs.find(x=>x.role===r);return `${r}: ${so?.status==="approved"?"✓":"✕"}`;}).join(" · ")}</div></div></div>{!allPassed&&<div style={{padding:8,background:T.rdA,borderRadius:6,fontSize:11,color:T.rd2,marginTop:8}}>⚠ Gate blocked: {!passed?`Score ${st.score} below minimum ${GATE_CONFIG.minScore}. `:""}{!signoffsMet?`Missing sign-offs: ${GATE_CONFIG.requiredSignoffs.filter(r=>!s.signoffs.find(so=>so.role===r&&so.status==="approved")).join(", ")}`:""}</div>}</div>;})()}</Crd>

    <Crd className="fu s2" style={{marginBottom:14}}><Lbl>📜 Compliance Certificate</Lbl><div style={{padding:14,background:T.sf2,borderRadius:7,textAlign:"center"}}><div style={{fontSize:13,fontWeight:700,color:T.tx}}>Generate Auditor-Ready Certificate</div><div style={{fontSize:11,color:T.tx3,marginTop:4}}>Includes: analysis summary, risk assessment, regulation mappings, sign-offs, timestamps.</div><div style={{display:"flex",justifyContent:"center",gap:6,marginTop:10}}><Btn v="primary" sz="sm">📜 Generate PDF Certificate</Btn><Btn v="ghost" sz="sm">📧 Email to Auditor</Btn></div></div></Crd>

    <Crd className="fu s3" style={{marginBottom:14}}><Lbl>📡 Drift Monitor</Lbl>{s.drift.active?<div><div style={{display:"flex",justifyContent:"space-between",fontSize:11}}><span style={{color:T.tx2}}>Schedule: {s.drift.schedule}</span><span style={{color:T.tx2}}>Last: {s.drift.lastRun}</span><span style={{color:T.tx2}}>Next: {s.drift.nextRun}</span></div>{s.drift.scoreDelta<0&&<div style={{padding:8,background:T.rdA,borderRadius:6,fontSize:11,color:T.rd2,marginTop:8}}>⚠ Drift detected: Score changed by {s.drift.scoreDelta} points since last analysis.</div>}{s.drift.scoreDelta===0&&<div style={{padding:8,background:T.gnA,borderRadius:6,fontSize:11,color:T.gn2,marginTop:8}}>✓ No drift detected. Risk profile stable.</div>}</div>:<div style={{fontSize:11,color:T.tx3}}>Drift monitoring not active for this session. <Btn v="ghost" sz="xs" s={{marginLeft:8}}>Enable</Btn></div>}</Crd>

    <Crd className="fu s4"><Lbl>🔒 Audit Trail</Lbl>{[{a:"Session created",t:s.date,u:"system"},{a:"Pipeline completed",t:s.date,u:"analysis-svc"},...s.signoffs.filter(so=>so.status!=="pending").map(so=>({a:`${so.role} sign-off: ${so.status}`,t:so.at,u:so.user}))].map((e,i)=><div key={i} style={{display:"flex",justifyContent:"space-between",padding:"6px 0",borderBottom:`1px solid ${T.bd}`,fontSize:11}}><span style={{color:T.tx2}}>{e.a}</span><span style={{color:T.tx4,fontFamily:M}}>{e.u} · {e.t}</span></div>)}</Crd>
  </div>}
  </div>;
}

// ── Compare View ──
function CompareView({idA,idB,onBack}){
  const a=S_DATA.find(s=>s.id===idA);const b=S_DATA.find(s=>s.id===idB);if(!a||!b)return null;
  return <div style={{maxWidth:960,margin:"0 auto",paddingTop:20}}><div style={{display:"flex",alignItems:"center",gap:10,marginBottom:20}}><Btn v="ghost" sz="xs" onClick={onBack}>← Back</Btn><h1 style={{fontSize:20,fontWeight:800,color:T.tx}}>⚡ Session Comparison</h1></div>
  <div style={{display:"grid",gridTemplateColumns:"1fr 1fr",gap:14}}>
  {[a,b].map((s,i)=><Crd key={i}><div style={{display:"flex",alignItems:"center",gap:6,marginBottom:12}}><span style={{fontSize:18}}>{s.icon}</span><div><div style={{fontSize:13,fontWeight:700,color:T.tx}}>{s.title}</div><div style={{fontSize:10,color:T.tx4}}>{s.date}</div></div></div>
  <div style={{textAlign:"center",marginBottom:12}}><CS score={s.st.score} sz={70}/></div>
  <div style={{display:"grid",gridTemplateColumns:"repeat(4,1fr)",gap:6,marginBottom:12}}>{[{l:"Risks",v:s.st.risks,c:T.or},{l:"Tests",v:s.st.tests,c:T.tl},{l:"Guards",v:s.st.guard,c:T.pr2},{l:"Check",v:s.st.check,c:T.gn}].map((x,j)=><div key={j} style={{textAlign:"center",padding:6,background:T.sf2,borderRadius:6}}><div style={{fontSize:16,fontWeight:800,color:x.c}}>{x.v}</div><div style={{fontSize:8,color:T.tx4}}>{x.l}</div></div>)}</div>
  <Lbl>EU Tier</Lbl><Bdg c={s.euTier==="High-Risk"?"rd":"or"} sz="xs">{s.euTier}</Bdg>
  <Lbl style={{marginTop:12}}>Risks</Lbl>{s.risks.map((r,j)=><div key={j} style={{fontSize:10,color:T.tx2,padding:"3px 0"}}>{r.id}: {r.n} — <span style={{color:r.s==="High"?T.rd:T.or}}>{r.s}</span></div>)}
  <Lbl style={{marginTop:12}}>Sign-offs</Lbl>{s.signoffs.map((so,j)=><div key={j} style={{fontSize:10,color:T.tx2,padding:"2px 0"}}>{so.role}: <span style={{color:so.status==="approved"?T.gn:so.status==="rejected"?T.rd:T.or}}>{so.status}</span></div>)}
  </Crd>)}
  </div>
  {/* Score diff */}
  <Crd style={{marginTop:14}}><Lbl>Score Difference</Lbl><div style={{display:"flex",alignItems:"center",justifyContent:"center",gap:20}}><div style={{textAlign:"center"}}><div style={{fontSize:24,fontWeight:800,color:a.st.score>=b.st.score?T.gn:T.rd}}>{a.st.score}</div><div style={{fontSize:10,color:T.tx4}}>{a.title.slice(0,20)}...</div></div><div style={{fontSize:20,color:T.tx3}}>vs</div><div style={{textAlign:"center"}}><div style={{fontSize:24,fontWeight:800,color:b.st.score>=a.st.score?T.gn:T.rd}}>{b.st.score}</div><div style={{fontSize:10,color:T.tx4}}>{b.title.slice(0,20)}...</div></div><div style={{padding:"8px 16px",background:T.sf2,borderRadius:7}}><div style={{fontSize:16,fontWeight:800,color:a.st.score-b.st.score>0?T.gn:a.st.score-b.st.score<0?T.rd:T.tx}}>{a.st.score-b.st.score>0?"+":""}{a.st.score-b.st.score}</div><div style={{fontSize:9,color:T.tx4}}>delta</div></div></div></Crd>
  </div>;
}

// ── Admin ──
function Admin(){const[tab,sT]=useState("history");const total=AUDIT_LOG.length;const failed=AUDIT_LOG.filter(l=>l.status==="failed").length;return <div style={{maxWidth:1060,margin:"0 auto",paddingTop:24}}><h1 className="fu" style={{fontSize:24,fontWeight:800,color:T.tx,marginBottom:20}}>Developer Dashboard</h1><div className="fu s1" style={{display:"grid",gridTemplateColumns:"repeat(4,1fr)",gap:12,marginBottom:20}}>{[{l:"TOTAL USERS",v:3,s:"registered accounts"},{l:"TOTAL SESSIONS",v:47,s:"analyses run"},{l:"LOGINS TODAY",v:9,s:"successful"},{l:"FAILED TODAY",v:failed,s:"failed attempts",c:T.rd}].map((x,i)=><Crd key={i} style={{padding:16}}><div style={{fontSize:9,fontWeight:600,color:T.tx4,letterSpacing:1}}>{x.l}</div><div style={{fontSize:28,fontWeight:800,color:x.c||T.tx}}>{x.v}</div><div style={{fontSize:10,color:T.tx4,marginTop:2}}>{x.s}</div></Crd>)}</div>
<div className="fu s2" style={{display:"flex",gap:4,marginBottom:14}}>{[{k:"users",l:"👥 Users"},{k:"history",l:"📋 Login History"},{k:"regulations",l:"🏛 Regulation Updates"}].map(t=><Btn key={t.k} v={tab===t.k?"primary":"ghost"} sz="xs" onClick={()=>sT(t.k)}>{t.l}</Btn>)}</div>
{tab==="history"&&<Crd className="fu s3" style={{padding:0,overflow:"hidden"}}><div style={{display:"flex",justifyContent:"space-between",padding:"12px 16px",borderBottom:`1px solid ${T.bd}`}}><span style={{fontSize:14,fontWeight:700,color:T.tx}}>Login History</span><span style={{fontSize:11,color:T.tx3}}>{total} events</span></div><div style={{display:"grid",gridTemplateColumns:"100px 1fr 70px 110px 90px",padding:"6px 16px",background:T.sf2,borderBottom:`1px solid ${T.bd}`}}>{["TIME","EMAIL","STATUS","REASON","IP"].map(h=><div key={h} style={{fontSize:9,fontWeight:700,color:T.tx4}}>{h}</div>)}</div><div style={{maxHeight:400,overflow:"auto"}}>{AUDIT_LOG.map((r,i)=><div key={i} style={{display:"grid",gridTemplateColumns:"100px 1fr 70px 110px 90px",padding:"8px 16px",borderBottom:`1px solid ${T.bd}`}}><div style={{fontSize:11,color:T.tx2,fontFamily:M}}>{r.time}</div><div style={{fontSize:11,color:T.tx}}>{r.email}</div><div><Bdg c={r.status==="success"?"gn":"rd"} sz="xs">{r.status==="success"?"✓":"✕"}</Bdg></div><div style={{fontSize:11,color:T.tx2}}>{r.reason}</div><div style={{fontSize:10,color:T.tx3,fontFamily:M}}>{r.ip}</div></div>)}</div><div style={{display:"flex",justifyContent:"space-between",padding:"8px 16px",borderTop:`1px solid ${T.bd}`}}><Btn v="ghost" sz="xs">← Prev</Btn><span style={{fontSize:11,color:T.tx3}}>Page 1 of 1</span><Btn v="ghost" sz="xs">Next →</Btn></div></Crd>}
{tab==="users"&&<Crd className="fu s3"><Lbl>Registered Users</Lbl>{[{e:"admin@launchguard.dev",l:"02 Mar 22:48",n:42},{e:"heatmap_test@test.dev",l:"02 Mar 22:31",n:3},{e:"test@example.com",l:"28 Feb 08:22",n:2}].map((u,i)=><div key={i} style={{display:"flex",justifyContent:"space-between",padding:"8px 0",borderBottom:i<2?`1px solid ${T.bd}`:"none"}}><span style={{fontSize:12,color:T.tx}}>{u.e}</span><span style={{fontSize:11,color:T.tx3,fontFamily:M}}>{u.l}</span><span style={{fontSize:12,color:T.bl2,fontWeight:600}}>{u.n} sessions</span></div>)}</Crd>}
{tab==="regulations"&&<Crd className="fu s3"><Lbl>Regulation Frameworks</Lbl>{REG_FRAMEWORKS.map((f,i)=><div key={i} style={{padding:10,background:T.sf2,borderRadius:7,marginBottom:6,display:"flex",justifyContent:"space-between",alignItems:"center"}}><div><div style={{fontSize:12,fontWeight:700,color:T.tx}}>{f.name} <span style={{fontWeight:400,color:T.tx3}}>({f.version})</span></div><div style={{fontSize:10,color:T.tx4,marginTop:2}}>{f.jurisdiction} · {f.reqs} requirements</div></div><div style={{display:"flex",gap:4}}><Bdg c="gn" sz="xs">{f.status}</Bdg><Btn v="ghost" sz="xs">View</Btn></div></div>)}<div style={{marginTop:12,padding:10,background:T.orA,borderRadius:7,fontSize:11,color:T.or2}}>⏳ 2 pending regulation updates awaiting review (Canada AIDA, UK DSIT)</div></Crd>}
</div>;}

// ── Settings ──
function Settings(){const[tab,sT]=useState("teams");return <div style={{maxWidth:560,margin:"0 auto",paddingTop:24}}><h1 className="fu" style={{fontSize:24,fontWeight:800,color:T.tx,marginBottom:20}}>Settings</h1><Crd className="fu s1"><div style={{display:"flex",gap:0,marginBottom:14,borderBottom:`1px solid ${T.bd}`}}>{[{k:"teams",l:"🏢 Teams"},{k:"api",l:"🔑 API Keys"},{k:"int",l:"🔌 Integrations"},{k:"gates",l:"🚦 Gates"}].map(t=><button key={t.k} onClick={()=>sT(t.k)} style={{background:"transparent",border:"none",color:tab===t.k?T.tx:T.tx4,fontSize:12,fontWeight:tab===t.k?600:400,padding:"8px 12px",cursor:"pointer",borderBottom:tab===t.k?`2px solid ${T.pr2}`:"2px solid transparent",fontFamily:F}}>{t.l}</button>)}</div>
{tab==="teams"&&<div><div style={{padding:12,background:T.sf2,borderRadius:7,marginBottom:12}}><div style={{display:"flex",justifyContent:"space-between"}}><div style={{display:"flex",alignItems:"center",gap:6}}><div style={{width:7,height:7,borderRadius:"50%",background:T.gn}}/><span style={{fontSize:13,fontWeight:700,color:T.tx}}>LG</span></div><Bdg c="pr" sz="xs">OWNER</Bdg></div><div style={{display:"flex",gap:4,marginTop:8}}>{["📧 Invite","👥 Members","🎨 Branding"].map((b,i)=><Btn key={i} v="ghost" sz="xs">{b}</Btn>)}</div></div><Btn v="primary" sz="sm" s={{width:"100%"}}>Create Workspace</Btn></div>}
{tab==="api"&&<div style={{textAlign:"center",padding:20}}><div style={{fontSize:12,color:T.tx3}}>Keys prefixed <code style={{color:T.pr2,fontFamily:M}}>lg_</code> for CI/CD.</div><Btn v="primary" sz="sm" s={{marginTop:10}}>+ Create API Key</Btn></div>}
{tab==="int"&&<div>{["Slack — Webhook on complete","Jira — Auto-create Must-Do issues","GitHub — PR risk comment","Linear — GraphQL checklist issues","Webhook — Custom HMAC-signed payload"].map((x,i)=><div key={i} style={{display:"flex",justifyContent:"space-between",padding:"7px 0",borderBottom:i<4?`1px solid ${T.bd}`:"none"}}><span style={{fontSize:11,color:T.tx2}}>{x}</span><Btn v="ghost" sz="xs">Configure</Btn></div>)}</div>}
{tab==="gates"&&<div><div style={{padding:12,background:T.sf2,borderRadius:7,border:`1px solid ${T.pr}18`,marginBottom:12}}><div style={{fontSize:13,fontWeight:700,color:T.tx}}>🚦 {GATE_CONFIG.name}</div><div style={{fontSize:11,color:T.tx3,marginTop:4}}>Type: {GATE_CONFIG.type} · Min Score: {GATE_CONFIG.minScore}</div><div style={{fontSize:11,color:T.tx3,marginTop:2}}>Required Sign-offs: {GATE_CONFIG.requiredSignoffs.join(", ")}</div><div style={{fontSize:11,color:T.tx3,marginTop:2}}>Required Frameworks: {GATE_CONFIG.requiredFrameworks.join(", ")}</div><div style={{display:"flex",gap:4,marginTop:8}}><Btn v="ghost" sz="xs">Edit</Btn><Btn v="danger" sz="xs">Disable</Btn></div></div><Btn v="primary" sz="sm" s={{width:"100%"}}>+ Create Gate</Btn></div>}
</Crd></div>;}

// ── New Check Modal ──
function NewCheck({onClose,onComplete}){const[t,sT]=useState("");const[d,sD]=useState("");const[running,sR]=useState(false);const[phase,sP]=useState(-1);
const run=()=>{if(!t.trim()&&!d.trim())return;sR(true);sP(0);setTimeout(()=>sP(1),3000);setTimeout(()=>sP(2),5500);setTimeout(()=>{sP(3);sR(false);setTimeout(()=>onComplete("legal"),800);},7500);};
return <div style={{position:"fixed",inset:0,background:"rgba(0,0,0,.6)",backdropFilter:"blur(6px)",zIndex:200,display:"flex",alignItems:"center",justifyContent:"center"}} onClick={!running?onClose:undefined}><div onClick={e=>e.stopPropagation()} style={{background:T.sf,border:`1px solid ${T.bd}`,borderRadius:14,padding:24,width:520,maxHeight:"90vh",overflow:"auto"}}><div style={{display:"flex",justifyContent:"space-between",alignItems:"center",marginBottom:16}}><div style={{fontSize:16,fontWeight:700,color:T.tx}}>🚀 New Readiness Check</div>{!running&&<button onClick={onClose} style={{background:"none",border:"none",color:T.tx3,fontSize:18,cursor:"pointer"}}>×</button>}</div>
{running&&<Pipeline phase={phase} showLogs={true}/>}
{!running&&<><div style={{marginBottom:12}}><label style={{fontSize:10,color:T.tx3,fontWeight:600,display:"block",marginBottom:4}}>Industry preset</label><select style={{width:"100%",background:T.sf2,border:`1px solid ${T.bd}`,borderRadius:7,color:T.tx2,fontSize:12,padding:"8px 10px",outline:"none",fontFamily:F}}><option>— No preset —</option><option>FinTech</option><option>HealthTech</option><option>LegalTech</option><option>B2B SaaS</option></select></div>
<div style={{marginBottom:12}}><label style={{fontSize:10,color:T.tx3,fontWeight:600,display:"block",marginBottom:4}}>Feature title</label><input value={t} onChange={e=>sT(e.target.value)} placeholder="e.g. AI-powered support reply" style={{width:"100%",background:T.sf2,border:`1px solid ${T.bd}`,borderRadius:7,color:T.tx,fontSize:12,padding:"8px 10px",outline:"none",fontFamily:F}}/></div>
<div style={{marginBottom:12}}><label style={{fontSize:10,color:T.tx3,fontWeight:600,display:"block",marginBottom:4}}>Description</label><textarea value={d} onChange={e=>sD(e.target.value)} placeholder="What are you building? Who uses it?" style={{width:"100%",minHeight:80,background:T.sf2,border:`1px solid ${T.bd}`,borderRadius:7,color:T.tx,fontSize:12,padding:"8px 10px",outline:"none",fontFamily:F,lineHeight:1.6,resize:"vertical"}}/></div>
<div style={{marginBottom:14}}><label style={{fontSize:10,color:T.tx3,fontWeight:600,display:"block",marginBottom:4}}>Release type</label><select style={{width:"100%",background:T.sf2,border:`1px solid ${T.bd}`,borderRadius:7,color:T.tx2,fontSize:12,padding:"8px 10px",outline:"none",fontFamily:F}}><option>MVP</option><option>Feature Update</option><option>Major Release</option></select></div></>}
<Btn v="cta" sz="lg" onClick={run} disabled={running} s={{width:"100%"}}>{running?`Processing... ${["Navigator","Sentinel","Herald","Done"][Math.min(phase,3)]}`:"Run Readiness Check →"}</Btn></div></div>;}

// ── Guide Panel ──
function GuidePanel({onClose}){return <div style={{position:"fixed",top:0,right:0,bottom:0,width:360,background:T.sf,borderLeft:`1px solid ${T.bd}`,zIndex:150,overflow:"auto",padding:"18px 20px",boxShadow:"-6px 0 24px rgba(0,0,0,.4)"}}><div style={{display:"flex",justifyContent:"space-between",alignItems:"center",marginBottom:18}}><div style={{fontSize:15,fontWeight:700,color:T.tx}}>📖 Guide</div><button onClick={onClose} style={{background:"none",border:"none",color:T.tx3,fontSize:16,cursor:"pointer"}}>×</button></div>
<Lbl>⚡ Quick Start</Lbl>{[{n:1,t:"Click + New Check",d:"From anywhere in the app."},{n:2,t:"Describe your feature",d:"Title + description. Use industry presets."},{n:3,t:"Watch the pipeline",d:"Navigator → Sentinel → Herald with live logs."},{n:4,t:"Explore results",d:"6 tabs: Overview, Spec & Risks, Tests, Docs, Regulation, Governance."}].map((s,i)=><div key={i} style={{display:"flex",gap:8,marginBottom:10}}><div style={{width:20,height:20,borderRadius:"50%",background:T.prA,border:`1px solid ${T.pr}50`,display:"flex",alignItems:"center",justifyContent:"center",color:T.pr2,fontSize:9,fontWeight:700,flexShrink:0}}>{s.n}</div><div><div style={{fontSize:11,fontWeight:600,color:T.tx}}>{s.t}</div><div style={{fontSize:10,color:T.tx3,marginTop:1}}>{s.d}</div></div></div>)}
<div style={{height:1,background:T.bd,margin:"14px 0"}}/>
<Lbl>🤖 Three Agents</Lbl>{[{n:"Navigator",c:T.gn,o:["Release Spec","Risk Register","Checklist"]},{n:"Sentinel",c:T.pr2,o:["Test Strategy","Test Cases","Guardrails"]},{n:"Herald",c:T.or2,o:["Release Notes","GTM Page","Pitch Deck"]}].map((a,i)=><div key={i} style={{padding:8,background:T.sf2,borderRadius:6,borderLeft:`3px solid ${a.c}`,marginBottom:6}}><div style={{fontSize:11,fontWeight:700,color:a.c}}>{a.n}</div>{a.o.map((o,j)=><div key={j} style={{fontSize:9,color:T.tx3,marginTop:1}}>→ {o}</div>)}</div>)}
<div style={{height:1,background:T.bd,margin:"14px 0"}}/>
<Lbl>🏛 Regulation Engine</Lbl><div style={{fontSize:10,color:T.tx2,lineHeight:1.5}}>Maps risks to 7 frameworks: EU AI Act, OWASP Top 10 LLM, NIST AI RMF, ISO 42001, GDPR, SOC 2, HIPAA. Auto-classifies EU AI Act risk tier. Compliance templates inject framework-specific checklist items.</div>
<div style={{height:1,background:T.bd,margin:"14px 0"}}/>
<Lbl>⚙️ Governance</Lbl>{[{l:"✍️ Sign-offs",d:"PM, Legal, QA, Security approvals"},{l:"🚦 Gates",d:"CI/CD + PR score threshold enforcement"},{l:"📜 Certificates",d:"Auditor-ready PDF with all evidence"},{l:"📡 Drift Monitor",d:"Weekly re-scan for regression"},{l:"⚡ Compare",d:"Side-by-side session diff"}].map((a,i)=><div key={i} style={{display:"flex",justifyContent:"space-between",padding:"4px 0",borderBottom:i<4?`1px solid ${T.bd}`:"none"}}><span style={{fontSize:10,color:T.tx}}>{a.l}</span><span style={{fontSize:9,color:T.tx4}}>{a.d}</span></div>)}
</div>;}

// ═══ MAIN APP ═══
export default function App(){
  const[pg,sPg]=useState("landing");const[auth,setAuth]=useState(false);const[sid,sSI]=useState(null);
  const[showNew,setSN]=useState(false);const[showGuide,setSG]=useState(false);
  const[compA,setCA]=useState(null);const[compB,setCB]=useState(null);

  const login=()=>{setAuth(true);sPg("dash");};const go=(p)=>{sPg(p);sSI(null);setCA(null);setCB(null);};
  const openSession=(id)=>{sSI(id);sPg("detail");};
  const session=sid?S_DATA.find(s=>s.id===sid):null;

  return <div style={{minHeight:"100vh",background:T.bg,fontFamily:F,color:T.tx}}><style>{CSS}</style>
  <nav style={{display:"flex",alignItems:"center",justifyContent:"space-between",padding:"7px 16px",borderBottom:`1px solid ${T.bd}`,background:T.sf,position:"sticky",top:0,zIndex:100}}>
    <div style={{display:"flex",alignItems:"center",gap:5,cursor:"pointer"}} onClick={()=>auth?go("dash"):go("landing")}><span style={{color:T.yl,fontSize:13}}>⚡</span><span style={{fontSize:14,fontWeight:700,color:T.tx,letterSpacing:.2}}>LaunchGuard</span></div>
    {auth?<><div style={{display:"flex",alignItems:"center",gap:2}}>
      {[{k:"dash",l:"Dashboard",i:"📊"},{k:"sessions",l:"Sessions",i:"📋"},{k:"admin",l:"Admin",i:"🔒"},{k:"settings",l:"Settings",i:"⚙"}].map(n=>{const act=pg===n.k||(n.k==="sessions"&&(pg==="detail"||pg==="compare"));return <button key={n.k} onClick={()=>go(n.k)} style={{display:"flex",alignItems:"center",gap:3,padding:"5px 10px",borderRadius:6,fontSize:11,fontWeight:act?600:400,cursor:"pointer",fontFamily:F,border:n.k==="admin"&&pg==="admin"?`1px solid ${T.or}40`:"none",background:act?(n.k==="admin"?T.orA:T.sf3):"transparent",color:act?(n.k==="admin"?T.or2:T.tx):T.tx3}}><span style={{fontSize:9}}>{n.i}</span>{n.l}</button>;})}
      <Btn v="primary" sz="xs" onClick={()=>setSN(true)} s={{marginLeft:6}}>+ New Check</Btn>
      <button onClick={()=>setSG(p=>!p)} style={{marginLeft:4,display:"flex",alignItems:"center",gap:3,padding:"5px 10px",borderRadius:6,background:showGuide?T.pr:"transparent",border:`1px solid ${showGuide?T.pr:T.bd}`,color:showGuide?"#fff":T.tx3,fontSize:11,fontWeight:500,cursor:"pointer",fontFamily:F}}>📖 Guide</button>
    </div>
    <div style={{display:"flex",alignItems:"center",gap:5}}><div style={{display:"flex",alignItems:"center",gap:3,padding:"4px 8px",borderRadius:6,background:T.sf2,border:`1px solid ${T.bd}`}}><div style={{width:16,height:16,borderRadius:"50%",background:T.gn,display:"flex",alignItems:"center",justifyContent:"center",fontSize:8,fontWeight:700,color:T.bg}}>S</div><span style={{fontSize:10,color:T.tx}}>Super Admin</span></div><Btn v="danger" sz="xs" onClick={()=>{setAuth(false);go("landing")}}>Sign out</Btn></div></>
    :<div style={{display:"flex",gap:5}}><Btn v="ghost" sz="xs" onClick={login}>Sign In</Btn><Btn v="primary" sz="xs" onClick={login}>Sign Up Free →</Btn></div>}
  </nav>

  <div style={{padding:"0 16px 40px"}}>
    {pg==="landing"&&<Landing onLogin={login}/>}
    {pg==="dash"&&<Dashboard onNew={()=>setSN(true)} onOpen={openSession}/>}
    {pg==="sessions"&&<SessionsList onOpen={openSession} onNew={()=>setSN(true)} onCompare={(a,b)=>{setCA(a);setCB(b);sPg("compare");}}/>}
    {pg==="detail"&&session&&<SessionDetail session={session} onBack={()=>go("sessions")}/>}
    {pg==="compare"&&compA&&compB&&<CompareView idA={compA} idB={compB} onBack={()=>go("sessions")}/>}
    {pg==="admin"&&<Admin/>}
    {pg==="settings"&&<Settings/>}
  </div>

  {showNew&&<NewCheck onClose={()=>setSN(false)} onComplete={(id)=>{setSN(false);openSession(id);}}/>}
  {showGuide&&<GuidePanel onClose={()=>setSG(false)}/>}

  <div style={{textAlign:"center",padding:"10px",borderTop:`1px solid ${T.bd}`,fontSize:9,color:T.tx4}}>⚡ LaunchGuard v3 — AI-generated outputs require human review. Regulation data is not legal advice.</div>
  </div>;
}
